services:
  web:
    build:
      args:
        ENVIRONMENT: development
    labels: !override
      com.chameth.vhost: "dev.simonmott.co.uk"
    volumes:
      - "./data/dev-robots.txt:/usr/share/nginx/html/robots.txt"
